from setuptools import setup, find_packages

setup(
    name='vigorish',
    version='0.1',
    py_modules=['vig'],
    install_requires=[
        'alembic',
        'boto3',
        'Click',
        'fuzzywuzzy',
        'lxml',
        'pandas',
        'psycopg2-binary',
        'python-dotenv',
        'python-levenshtein',
        'requests',
        'selenium',
        'SQLAlchemy',
        'tqdm',
        'tzlocal',
        'urllib3',
        'w3lib'
    ],
    entry_points='''
        [console_scripts]
        vig=vig:cli
    ''',
)