from dacite.core import from_dict

from vigorish.data.metrics import BatStatsMetrics, PitchFxMetricsCollection, PitchStatsMetrics
from vigorish.data.player_data import PlayerData
from vigorish.enums import DefensePosition

from .conftest import BBREF_GAME_ID


def test_bat_stats(vig_app):
    bat_stats_for_career_dict = {
        "year": 0,
        "team_id_bbref": "",
        "opponent_team_id_bbref": "",
        "mlb_id": 545361,
        "bbref_id": "troutmi01",
        "stint_number": 0,
        "total_games": 1,
        "avg": 0.8,
        "obp": 0.8,
        "slg": 1.6,
        "ops": 2.4,
        "iso": 0.8,
        "bb_rate": 0.0,
        "k_rate": 0.0,
        "contact_rate": 1.0,
        "plate_appearances": 5,
        "at_bats": 5,
        "hits": 4,
        "runs_scored": 2,
        "rbis": 3,
        "bases_on_balls": 0,
        "strikeouts": 0,
        "doubles": 1,
        "triples": 0,
        "homeruns": 1,
        "stolen_bases": 0,
        "caught_stealing": 1,
        "hit_by_pitch": 0,
        "intentional_bb": 0,
        "gdp": 0,
        "sac_fly": 0,
        "sac_hit": 0,
        "total_pitches": 19,
        "total_strikes": 11,
        "wpa_bat": 0.145,
        "wpa_bat_pos": 0.166,
        "wpa_bat_neg": -0.021,
        "re24_bat": 2.9,
    }

    bat_stats_by_year_dict = {
        "year": 2019,
        "team_id_bbref": "",
        "opponent_team_id_bbref": "",
        "mlb_id": 545361,
        "bbref_id": "troutmi01",
        "stint_number": 0,
        "total_games": 1,
        "avg": 0.8,
        "obp": 0.8,
        "slg": 1.6,
        "ops": 2.4,
        "iso": 0.8,
        "bb_rate": 0.0,
        "k_rate": 0.0,
        "contact_rate": 1.0,
        "plate_appearances": 5,
        "at_bats": 5,
        "hits": 4,
        "runs_scored": 2,
        "rbis": 3,
        "bases_on_balls": 0,
        "strikeouts": 0,
        "doubles": 1,
        "triples": 0,
        "homeruns": 1,
        "stolen_bases": 0,
        "caught_stealing": 1,
        "hit_by_pitch": 0,
        "intentional_bb": 0,
        "gdp": 0,
        "sac_fly": 0,
        "sac_hit": 0,
        "total_pitches": 19,
        "total_strikes": 11,
        "wpa_bat": 0.145,
        "wpa_bat_pos": 0.166,
        "wpa_bat_neg": -0.021,
        "re24_bat": 2.9,
    }

    bat_stats_by_team_dict = {
        "at_bats": 5,
        "avg": 0.8,
        "bases_on_balls": 0,
        "bat_order": 0,
        "bb_rate": 0.0,
        "bbref_id": "troutmi01",
        "caught_stealing": 1,
        "def_position": DefensePosition.NONE,
        "doubles": 1,
        "gdp": 0,
        "hit_by_pitch": 0,
        "hits": 4,
        "homeruns": 1,
        "intentional_bb": 0,
        "is_starter": False,
        "iso": 0.8,
        "k_rate": 0.0,
        "contact_rate": 1.0,
        "mlb_id": 545361,
        "obp": 0.8,
        "opponent_team_id_bbref": "",
        "ops": 2.4,
        "plate_appearances": 5,
        "rbis": 3,
        "re24_bat": 2.9,
        "runs_scored": 2,
        "sac_fly": 0,
        "sac_hit": 0,
        "slg": 1.6,
        "stint_number": 0,
        "stolen_bases": 0,
        "strikeouts": 0,
        "team_id_bbref": "",
        "total_games": 1,
        "total_pitches": 19,
        "total_strikes": 11,
        "triples": 0,
        "wpa_bat": 0.145,
        "wpa_bat_neg": -0.021,
        "wpa_bat_pos": 0.166,
        "year": 0,
    }

    bat_stats_by_team_by_year_dict = {
        "at_bats": 5,
        "avg": 0.8,
        "bases_on_balls": 0,
        "bat_order": 0,
        "bb_rate": 0.0,
        "bbref_id": "troutmi01",
        "caught_stealing": 1,
        "def_position": DefensePosition.NONE,
        "doubles": 1,
        "gdp": 0,
        "hit_by_pitch": 0,
        "hits": 4,
        "homeruns": 1,
        "intentional_bb": 0,
        "is_starter": False,
        "iso": 0.8,
        "k_rate": 0.0,
        "contact_rate": 1.0,
        "mlb_id": 545361,
        "obp": 0.8,
        "opponent_team_id_bbref": "",
        "ops": 2.4,
        "plate_appearances": 5,
        "rbis": 3,
        "re24_bat": 2.9,
        "runs_scored": 2,
        "sac_fly": 0,
        "sac_hit": 0,
        "slg": 1.6,
        "stint_number": 1,
        "stolen_bases": 0,
        "strikeouts": 0,
        "team_id_bbref": "",
        "total_games": 1,
        "total_pitches": 19,
        "total_strikes": 11,
        "triples": 0,
        "wpa_bat": 0.145,
        "wpa_bat_neg": -0.021,
        "wpa_bat_pos": 0.166,
        "year": 2019,
    }

    bat_stats_by_opp_team_dict = {
        "at_bats": 5,
        "avg": 0.8,
        "bases_on_balls": 0,
        "bat_order": 0,
        "bb_rate": 0.0,
        "bbref_id": "troutmi01",
        "caught_stealing": 1,
        "def_position": DefensePosition.NONE,
        "doubles": 1,
        "gdp": 0,
        "hit_by_pitch": 0,
        "hits": 4,
        "homeruns": 1,
        "intentional_bb": 0,
        "is_starter": False,
        "iso": 0.8,
        "k_rate": 0.0,
        "contact_rate": 1.0,
        "mlb_id": 545361,
        "obp": 0.8,
        "opponent_team_id_bbref": "TOR",
        "ops": 2.4,
        "plate_appearances": 5,
        "rbis": 3,
        "re24_bat": 2.9,
        "runs_scored": 2,
        "sac_fly": 0,
        "sac_hit": 0,
        "slg": 1.6,
        "stint_number": 0,
        "stolen_bases": 0,
        "strikeouts": 0,
        "team_id_bbref": "",
        "total_games": 1,
        "total_pitches": 19,
        "total_strikes": 11,
        "triples": 0,
        "wpa_bat": 0.145,
        "wpa_bat_neg": -0.021,
        "wpa_bat_pos": 0.166,
        "year": 0,
    }

    bat_stats_by_opp_team_by_year_dict = {
        "at_bats": 5,
        "avg": 0.8,
        "bases_on_balls": 0,
        "bat_order": 0,
        "bb_rate": 0.0,
        "bbref_id": "troutmi01",
        "caught_stealing": 1,
        "def_position": DefensePosition.NONE,
        "doubles": 1,
        "gdp": 0,
        "hit_by_pitch": 0,
        "hits": 4,
        "homeruns": 1,
        "intentional_bb": 0,
        "is_starter": False,
        "iso": 0.8,
        "k_rate": 0.0,
        "contact_rate": 1.0,
        "mlb_id": 545361,
        "obp": 0.8,
        "opponent_team_id_bbref": "TOR",
        "ops": 2.4,
        "plate_appearances": 5,
        "rbis": 3,
        "re24_bat": 2.9,
        "runs_scored": 2,
        "sac_fly": 0,
        "sac_hit": 0,
        "slg": 1.6,
        "stint_number": 0,
        "stolen_bases": 0,
        "strikeouts": 0,
        "team_id_bbref": "",
        "total_games": 1,
        "total_pitches": 19,
        "total_strikes": 11,
        "triples": 0,
        "wpa_bat": 0.145,
        "wpa_bat_neg": -0.021,
        "wpa_bat_pos": 0.166,
        "year": 2019,
    }

    bat_stats_for_career = from_dict(data_class=BatStatsMetrics, data=bat_stats_for_career_dict)
    bat_stats_by_year = from_dict(data_class=BatStatsMetrics, data=bat_stats_by_year_dict)
    bat_stats_by_team = from_dict(data_class=BatStatsMetrics, data=bat_stats_by_team_dict)
    bat_stats_by_team_by_year = from_dict(data_class=BatStatsMetrics, data=bat_stats_by_team_by_year_dict)
    bat_stats_by_opp_team = from_dict(data_class=BatStatsMetrics, data=bat_stats_by_opp_team_dict)
    bat_stats_by_opp_team_by_year = from_dict(data_class=BatStatsMetrics, data=bat_stats_by_opp_team_by_year_dict)

    player_data = PlayerData(vig_app, 545361)
    assert player_data.bat_stats_for_career == bat_stats_for_career
    assert player_data.bat_stats_by_year == [bat_stats_by_year]
    assert player_data.bat_stats_by_team == [bat_stats_by_team]
    assert player_data.bat_stats_by_team_by_year == [bat_stats_by_team_by_year]
    assert player_data.bat_stats_by_opp_team == [bat_stats_by_opp_team]
    assert player_data.bat_stats_by_opp_team_by_year == [bat_stats_by_opp_team_by_year]


def test_pitch_stats(vig_app):
    pitch_stats_for_career_dict = {
        "year": 0,
        "team_id_bbref": "",
        "opponent_team_id_bbref": "",
        "mlb_id": 571882,
        "bbref_id": "lawde01",
        "stint_number": 0,
        "total_games": 1,
        "games_as_sp": 1,
        "games_as_rp": 0,
        "wins": 0,
        "losses": 0,
        "saves": 0,
        "innings_pitched": 1.0,
        "total_outs": 3,
        "batters_faced": 3,
        "runs": 0,
        "earned_runs": 0,
        "hits": 0,
        "homeruns": 0,
        "strikeouts": 2,
        "bases_on_balls": 0,
        "era": 0.0,
        "whip": 0.0,
        "k_per_nine": 18.0,
        "bb_per_nine": 0.0,
        "hr_per_nine": 0.0,
        "k_per_bb": 0.0,
        "k_rate": 0.667,
        "bb_rate": 0.0,
        "k_minus_bb": 0.667,
        "hr_per_fb": 0.0,
        "pitch_count": 17,
        "strikes": 11,
        "strikes_contact": 4,
        "strikes_swinging": 2,
        "strikes_looking": 5,
        "ground_balls": 0,
        "fly_balls": 1,
        "line_drives": 1,
        "unknown_type": 0,
        "inherited_runners": 0,
        "inherited_scored": 0,
        "wpa_pitch": 0.049,
        "re24_pitch": 0.5,
    }

    pitch_stats_as_sp_dict = {
        "year": 0,
        "team_id_bbref": "",
        "opponent_team_id_bbref": "",
        "mlb_id": 571882,
        "bbref_id": "lawde01",
        "stint_number": 0,
        "total_games": 1,
        "games_as_sp": 1,
        "games_as_rp": 0,
        "wins": 0,
        "losses": 0,
        "saves": 0,
        "innings_pitched": 1.0,
        "total_outs": 3,
        "batters_faced": 3,
        "runs": 0,
        "earned_runs": 0,
        "hits": 0,
        "homeruns": 0,
        "strikeouts": 2,
        "bases_on_balls": 0,
        "era": 0.0,
        "whip": 0.0,
        "k_per_nine": 18.0,
        "bb_per_nine": 0.0,
        "hr_per_nine": 0.0,
        "k_per_bb": 0.0,
        "k_rate": 0.667,
        "bb_rate": 0.0,
        "k_minus_bb": 0.667,
        "hr_per_fb": 0.0,
        "pitch_count": 17,
        "strikes": 11,
        "strikes_contact": 4,
        "strikes_swinging": 2,
        "strikes_looking": 5,
        "ground_balls": 0,
        "fly_balls": 1,
        "line_drives": 1,
        "unknown_type": 0,
        "inherited_runners": 0,
        "inherited_scored": 0,
        "wpa_pitch": 0.049,
        "re24_pitch": 0.5,
    }

    pitch_stats_as_rp = None

    pitch_stats_by_year_dict = {
        "year": 2019,
        "team_id_bbref": "",
        "opponent_team_id_bbref": "",
        "mlb_id": 571882,
        "bbref_id": "lawde01",
        "stint_number": 0,
        "total_games": 1,
        "games_as_sp": 1,
        "games_as_rp": 0,
        "wins": 0,
        "losses": 0,
        "saves": 0,
        "innings_pitched": 1.0,
        "total_outs": 3,
        "batters_faced": 3,
        "runs": 0,
        "earned_runs": 0,
        "hits": 0,
        "homeruns": 0,
        "strikeouts": 2,
        "bases_on_balls": 0,
        "era": 0.0,
        "whip": 0.0,
        "k_per_nine": 18.0,
        "bb_per_nine": 0.0,
        "hr_per_nine": 0.0,
        "k_per_bb": 0.0,
        "k_rate": 0.667,
        "bb_rate": 0.0,
        "k_minus_bb": 0.667,
        "hr_per_fb": 0.0,
        "pitch_count": 17,
        "strikes": 11,
        "strikes_contact": 4,
        "strikes_swinging": 2,
        "strikes_looking": 5,
        "ground_balls": 0,
        "fly_balls": 1,
        "line_drives": 1,
        "unknown_type": 0,
        "inherited_runners": 0,
        "inherited_scored": 0,
        "wpa_pitch": 0.049,
        "re24_pitch": 0.5,
    }

    pitch_stats_by_team_dict = {
        "year": 0,
        "team_id_bbref": "TOR",
        "opponent_team_id_bbref": "",
        "mlb_id": 571882,
        "bbref_id": "lawde01",
        "stint_number": 0,
        "total_games": 1,
        "games_as_sp": 1,
        "games_as_rp": 0,
        "wins": 0,
        "losses": 0,
        "saves": 0,
        "innings_pitched": 1.0,
        "total_outs": 3,
        "batters_faced": 3,
        "runs": 0,
        "earned_runs": 0,
        "hits": 0,
        "homeruns": 0,
        "strikeouts": 2,
        "bases_on_balls": 0,
        "era": 0.0,
        "whip": 0.0,
        "k_per_nine": 18.0,
        "bb_per_nine": 0.0,
        "hr_per_nine": 0.0,
        "k_per_bb": 0.0,
        "k_rate": 0.667,
        "bb_rate": 0.0,
        "k_minus_bb": 0.667,
        "hr_per_fb": 0.0,
        "pitch_count": 17,
        "strikes": 11,
        "strikes_contact": 4,
        "strikes_swinging": 2,
        "strikes_looking": 5,
        "ground_balls": 0,
        "fly_balls": 1,
        "line_drives": 1,
        "unknown_type": 0,
        "inherited_runners": 0,
        "inherited_scored": 0,
        "wpa_pitch": 0.049,
        "re24_pitch": 0.5,
    }

    pitch_stats_by_team_by_year_dict = {
        "year": 2019,
        "team_id_bbref": "TOR",
        "opponent_team_id_bbref": "",
        "mlb_id": 571882,
        "bbref_id": "lawde01",
        "stint_number": 1,
        "total_games": 1,
        "games_as_sp": 1,
        "games_as_rp": 0,
        "wins": 0,
        "losses": 0,
        "saves": 0,
        "innings_pitched": 1.0,
        "total_outs": 3,
        "batters_faced": 3,
        "runs": 0,
        "earned_runs": 0,
        "hits": 0,
        "homeruns": 0,
        "strikeouts": 2,
        "bases_on_balls": 0,
        "era": 0.0,
        "whip": 0.0,
        "k_per_nine": 18.0,
        "bb_per_nine": 0.0,
        "hr_per_nine": 0.0,
        "k_per_bb": 0.0,
        "k_rate": 0.667,
        "bb_rate": 0.0,
        "k_minus_bb": 0.667,
        "hr_per_fb": 0.0,
        "pitch_count": 17,
        "strikes": 11,
        "strikes_contact": 4,
        "strikes_swinging": 2,
        "strikes_looking": 5,
        "ground_balls": 0,
        "fly_balls": 1,
        "line_drives": 1,
        "unknown_type": 0,
        "inherited_runners": 0,
        "inherited_scored": 0,
        "wpa_pitch": 0.049,
        "re24_pitch": 0.5,
    }

    pitch_stats_by_opp_team_dict = {
        "year": 0,
        "team_id_bbref": "",
        "opponent_team_id_bbref": "LAA",
        "mlb_id": 571882,
        "bbref_id": "lawde01",
        "stint_number": 0,
        "total_games": 1,
        "games_as_sp": 1,
        "games_as_rp": 0,
        "wins": 0,
        "losses": 0,
        "saves": 0,
        "innings_pitched": 1.0,
        "total_outs": 3,
        "batters_faced": 3,
        "runs": 0,
        "earned_runs": 0,
        "hits": 0,
        "homeruns": 0,
        "strikeouts": 2,
        "bases_on_balls": 0,
        "era": 0.0,
        "whip": 0.0,
        "k_per_nine": 18.0,
        "bb_per_nine": 0.0,
        "hr_per_nine": 0.0,
        "k_per_bb": 0.0,
        "k_rate": 0.667,
        "bb_rate": 0.0,
        "k_minus_bb": 0.667,
        "hr_per_fb": 0.0,
        "pitch_count": 17,
        "strikes": 11,
        "strikes_contact": 4,
        "strikes_swinging": 2,
        "strikes_looking": 5,
        "ground_balls": 0,
        "fly_balls": 1,
        "line_drives": 1,
        "unknown_type": 0,
        "inherited_runners": 0,
        "inherited_scored": 0,
        "wpa_pitch": 0.049,
        "re24_pitch": 0.5,
    }

    pitch_stats_by_opp_team_by_year_dict = {
        "year": 2019,
        "team_id_bbref": "",
        "opponent_team_id_bbref": "LAA",
        "mlb_id": 571882,
        "bbref_id": "lawde01",
        "stint_number": 0,
        "total_games": 1,
        "games_as_sp": 1,
        "games_as_rp": 0,
        "wins": 0,
        "losses": 0,
        "saves": 0,
        "innings_pitched": 1.0,
        "total_outs": 3,
        "batters_faced": 3,
        "runs": 0,
        "earned_runs": 0,
        "hits": 0,
        "homeruns": 0,
        "strikeouts": 2,
        "bases_on_balls": 0,
        "era": 0.0,
        "whip": 0.0,
        "k_per_nine": 18.0,
        "bb_per_nine": 0.0,
        "hr_per_nine": 0.0,
        "k_per_bb": 0.0,
        "k_rate": 0.667,
        "bb_rate": 0.0,
        "k_minus_bb": 0.667,
        "hr_per_fb": 0.0,
        "pitch_count": 17,
        "strikes": 11,
        "strikes_contact": 4,
        "strikes_swinging": 2,
        "strikes_looking": 5,
        "ground_balls": 0,
        "fly_balls": 1,
        "line_drives": 1,
        "unknown_type": 0,
        "inherited_runners": 0,
        "inherited_scored": 0,
        "wpa_pitch": 0.049,
        "re24_pitch": 0.5,
    }

    pitch_stats_for_career = from_dict(data_class=PitchStatsMetrics, data=pitch_stats_for_career_dict)
    pitch_stats_as_sp = from_dict(data_class=PitchStatsMetrics, data=pitch_stats_as_sp_dict)
    pitch_stats_as_rp = None
    pitch_stats_by_year = from_dict(data_class=PitchStatsMetrics, data=pitch_stats_by_year_dict)
    pitch_stats_by_team = from_dict(data_class=PitchStatsMetrics, data=pitch_stats_by_team_dict)
    pitch_stats_by_team_by_year = from_dict(data_class=PitchStatsMetrics, data=pitch_stats_by_team_by_year_dict)
    pitch_stats_by_opp_team = from_dict(data_class=PitchStatsMetrics, data=pitch_stats_by_opp_team_dict)
    pitch_stats_by_opp_team_by_year = from_dict(data_class=PitchStatsMetrics, data=pitch_stats_by_opp_team_by_year_dict)

    player_data = PlayerData(vig_app, 571882)
    assert player_data.pitch_stats_for_career == pitch_stats_for_career
    assert player_data.pitch_stats_as_sp == pitch_stats_as_sp
    assert player_data.pitch_stats_as_rp == pitch_stats_as_rp
    assert player_data.pitch_stats_by_year == [pitch_stats_by_year]
    assert player_data.pitch_stats_by_team == [pitch_stats_by_team]
    assert player_data.pitch_stats_by_team_by_year == [pitch_stats_by_team_by_year]
    assert player_data.pitch_stats_by_opp_team == [pitch_stats_by_opp_team]
    assert player_data.pitch_stats_by_opp_team_by_year == [pitch_stats_by_opp_team_by_year]


def test_pitchfx_metrics_career(vig_app):
    pfx_metrics_career_ALL_dict = {
        "id": 176,
        "mlb_id": 571882,
        "p_throws": "R",
        "pitch_type": "ALL",
        "total_pitches": 17,
        "total_pa": 3,
        "total_at_bats": 3,
        "total_outs": 3,
        "total_hits": 0,
        "total_bb": 0,
        "total_k": 2,
        "avg": 0.0,
        "obp": 0.0,
        "slg": 0.0,
        "ops": 0.0,
        "iso": 0.0,
        "fly_ball_rate": 0.0,
        "ground_ball_rate": 0.0,
        "line_drive_rate": 1.0,
        "pop_up_rate": 0.0,
        "bb_rate": 0.0,
        "k_rate": 0.6666666666666666,
        "hr_per_fb": 0.0,
        "zone_rate": 0.5294117647058824,
        "called_strike_rate": 0.29411764705882354,
        "swinging_strike_rate": 0.11764705882352941,
        "whiff_rate": 0.3333333333333333,
        "csw_rate": 0.4117647058823529,
        "o_swing_rate": 0.25,
        "z_swing_rate": 0.4444444444444444,
        "swing_rate": 0.35294117647058826,
        "o_contact_rate": 0.5,
        "z_contact_rate": 0.75,
        "contact_rate": 0.66666666666666667,
        "total_swings": 6,
        "total_swings_made_contact": 4,
        "total_called_strikes": 5,
        "total_swinging_strikes": 2,
        "total_inside_strike_zone": 9,
        "total_outside_strike_zone": 8,
        "total_swings_inside_zone": 4,
        "total_swings_outside_zone": 2,
        "total_contact_inside_zone": 3,
        "total_contact_outside_zone": 1,
        "total_batted_balls": 1,
        "total_ground_balls": 0,
        "total_line_drives": 1,
        "total_fly_balls": 0,
        "total_pop_ups": 0,
        "total_singles": 0,
        "total_doubles": 0,
        "total_triples": 0,
        "total_homeruns": 0,
        "total_ibb": 0,
        "total_hbp": 0,
        "total_errors": 0,
        "total_sac_hit": 0,
        "total_sac_fly": 0,
        "total_unclear_results": 0,
        "pitch_type_int": 32803,
    }

    pfx_metrics_career_CU_dict = {
        "id": 176,
        "mlb_id": 571882,
        "p_throws": "R",
        "pitch_type": "CU",
        "total_pitches": 6,
        "total_pa": 0,
        "total_at_bats": 0,
        "total_outs": 0,
        "total_hits": 0,
        "total_bb": 0,
        "total_k": 0,
        "avg_speed": 78.69166666666666,
        "avg_pfx_x": 2.9116666666666666,
        "avg_pfx_z": -4.573333333333334,
        "avg_px": 0.006666666666666654,
        "avg_pz": 1.7850000000000001,
        "avg": 0.0,
        "obp": 0.0,
        "slg": 0.0,
        "ops": 0.0,
        "iso": 0.0,
        "fly_ball_rate": 0.0,
        "ground_ball_rate": 0.0,
        "line_drive_rate": 0.0,
        "pop_up_rate": 0.0,
        "bb_rate": 0.0,
        "k_rate": 0.0,
        "hr_per_fb": 0.0,
        "zone_rate": 0.5,
        "called_strike_rate": 0.5,
        "swinging_strike_rate": 0.0,
        "whiff_rate": 0.0,
        "csw_rate": 0.5,
        "o_swing_rate": 0.3333333333333333,
        "z_swing_rate": 0.0,
        "swing_rate": 0.16666666666666666,
        "o_contact_rate": 1.0,
        "z_contact_rate": 0.0,
        "contact_rate": 1.0,
        "total_swings": 1,
        "total_swings_made_contact": 1,
        "total_called_strikes": 3,
        "total_swinging_strikes": 0,
        "total_inside_strike_zone": 3,
        "total_outside_strike_zone": 3,
        "total_swings_inside_zone": 0,
        "total_swings_outside_zone": 1,
        "total_contact_inside_zone": 0,
        "total_contact_outside_zone": 1,
        "total_batted_balls": 0,
        "total_ground_balls": 0,
        "total_line_drives": 0,
        "total_fly_balls": 0,
        "total_pop_ups": 0,
        "total_singles": 0,
        "total_doubles": 0,
        "total_triples": 0,
        "total_homeruns": 0,
        "total_ibb": 0,
        "total_hbp": 0,
        "total_errors": 0,
        "total_sac_hit": 0,
        "total_sac_fly": 0,
        "total_unclear_results": 0,
    }

    pfx_metrics_career_FF_dict = {
        "id": 176,
        "mlb_id": 571882,
        "p_throws": "R",
        "pitch_type": "FF",
        "total_pitches": 6,
        "total_pa": 1,
        "total_at_bats": 1,
        "total_outs": 1,
        "total_hits": 0,
        "total_bb": 0,
        "total_k": 0,
        "avg_speed": 94.26,
        "avg_pfx_x": -1.2583333333333335,
        "avg_pfx_z": 8.69,
        "avg_px": -0.04999999999999999,
        "avg_pz": 3.306666666666667,
        "avg": 0.0,
        "obp": 0.0,
        "slg": 0.0,
        "ops": 0.0,
        "iso": 0.0,
        "fly_ball_rate": 0.0,
        "ground_ball_rate": 0.0,
        "line_drive_rate": 1.0,
        "pop_up_rate": 0.0,
        "bb_rate": 0.0,
        "k_rate": 0.0,
        "hr_per_fb": 0.0,
        "zone_rate": 0.5,
        "called_strike_rate": 0.16666666666666666,
        "swinging_strike_rate": 0.0,
        "whiff_rate": 0.0,
        "csw_rate": 0.16666666666666666,
        "o_swing_rate": 0.0,
        "z_swing_rate": 0.6666666666666666,
        "swing_rate": 0.3333333333333333,
        "o_contact_rate": 0.0,
        "z_contact_rate": 1.0,
        "contact_rate": 1.0,
        "total_swings": 2,
        "total_swings_made_contact": 2,
        "total_called_strikes": 1,
        "total_swinging_strikes": 0,
        "total_inside_strike_zone": 3,
        "total_outside_strike_zone": 3,
        "total_swings_inside_zone": 2,
        "total_swings_outside_zone": 0,
        "total_contact_inside_zone": 2,
        "total_contact_outside_zone": 0,
        "total_batted_balls": 1,
        "total_ground_balls": 0,
        "total_line_drives": 1,
        "total_fly_balls": 0,
        "total_pop_ups": 0,
        "total_singles": 0,
        "total_doubles": 0,
        "total_triples": 0,
        "total_homeruns": 0,
        "total_ibb": 0,
        "total_hbp": 0,
        "total_errors": 0,
        "total_sac_hit": 0,
        "total_sac_fly": 0,
        "total_unclear_results": 0,
    }

    pfx_metrics_career_CH_dict = {
        "id": 176,
        "mlb_id": 571882,
        "p_throws": "R",
        "pitch_type": "CH",
        "total_pitches": 3,
        "total_pa": 1,
        "total_at_bats": 1,
        "total_outs": 1,
        "total_hits": 0,
        "total_bb": 0,
        "total_k": 1,
        "avg_speed": 86.03666666666668,
        "avg_pfx_x": -6.37,
        "avg_pfx_z": 7.136666666666667,
        "avg_px": -0.3,
        "avg_pz": 2.3699999999999997,
        "avg": 0.0,
        "obp": 0.0,
        "slg": 0.0,
        "ops": 0.0,
        "iso": 0.0,
        "fly_ball_rate": 0.0,
        "ground_ball_rate": 0.0,
        "line_drive_rate": 0.0,
        "pop_up_rate": 0.0,
        "bb_rate": 0.0,
        "k_rate": 1.0,
        "hr_per_fb": 0.0,
        "zone_rate": 1.0,
        "called_strike_rate": 0.3333333333333333,
        "swinging_strike_rate": 0.3333333333333333,
        "whiff_rate": 0.5,
        "csw_rate": 0.6666666666666666,
        "o_swing_rate": 0.0,
        "z_swing_rate": 0.6666666666666666,
        "swing_rate": 0.6666666666666666,
        "o_contact_rate": 0.0,
        "z_contact_rate": 0.5,
        "contact_rate": 0.5,
        "total_swings": 2,
        "total_swings_made_contact": 1,
        "total_called_strikes": 1,
        "total_swinging_strikes": 1,
        "total_inside_strike_zone": 3,
        "total_outside_strike_zone": 0,
        "total_swings_inside_zone": 2,
        "total_swings_outside_zone": 0,
        "total_contact_inside_zone": 1,
        "total_contact_outside_zone": 0,
        "total_batted_balls": 0,
        "total_ground_balls": 0,
        "total_line_drives": 0,
        "total_fly_balls": 0,
        "total_pop_ups": 0,
        "total_singles": 0,
        "total_doubles": 0,
        "total_triples": 0,
        "total_homeruns": 0,
        "total_ibb": 0,
        "total_hbp": 0,
        "total_errors": 0,
        "total_sac_hit": 0,
        "total_sac_fly": 0,
        "total_unclear_results": 0,
    }

    pfx_metrics_career_SL_dict = {
        "id": 176,
        "mlb_id": 571882,
        "p_throws": "R",
        "pitch_type": "SL",
        "total_pitches": 2,
        "total_pa": 1,
        "total_at_bats": 1,
        "total_outs": 1,
        "total_hits": 0,
        "total_bb": 0,
        "total_k": 1,
        "avg_speed": 84.225,
        "avg_pfx_x": 1.83,
        "avg_pfx_z": -1.2650000000000001,
        "avg_px": 0.845,
        "avg_pz": 0.54,
        "avg": 0.0,
        "obp": 0.0,
        "slg": 0.0,
        "ops": 0.0,
        "iso": 0.0,
        "fly_ball_rate": 0.0,
        "ground_ball_rate": 0.0,
        "line_drive_rate": 0.0,
        "pop_up_rate": 0.0,
        "bb_rate": 0.0,
        "k_rate": 1.0,
        "hr_per_fb": 0.0,
        "zone_rate": 0.0,
        "called_strike_rate": 0.0,
        "swinging_strike_rate": 0.5,
        "whiff_rate": 1.0,
        "csw_rate": 0.5,
        "o_swing_rate": 0.5,
        "z_swing_rate": 0.0,
        "swing_rate": 0.5,
        "o_contact_rate": 0.0,
        "z_contact_rate": 0.0,
        "contact_rate": 0.0,
        "total_swings": 1,
        "total_swings_made_contact": 0,
        "total_called_strikes": 0,
        "total_swinging_strikes": 1,
        "total_inside_strike_zone": 0,
        "total_outside_strike_zone": 2,
        "total_swings_inside_zone": 0,
        "total_swings_outside_zone": 1,
        "total_contact_inside_zone": 0,
        "total_contact_outside_zone": 0,
        "total_batted_balls": 0,
        "total_ground_balls": 0,
        "total_line_drives": 0,
        "total_fly_balls": 0,
        "total_pop_ups": 0,
        "total_singles": 0,
        "total_doubles": 0,
        "total_triples": 0,
        "total_homeruns": 0,
        "total_ibb": 0,
        "total_hbp": 0,
        "total_errors": 0,
        "total_sac_hit": 0,
        "total_sac_fly": 0,
        "total_unclear_results": 0,
    }

    pfx_metrics_career_by_pitchtype = [
        pfx_metrics_career_CU_dict,
        pfx_metrics_career_FF_dict,
        pfx_metrics_career_CH_dict,
        pfx_metrics_career_SL_dict,
    ]
    pfx_metrics_vs_all_career = PitchFxMetricsCollection.from_query_results(
        pfx_metrics_career_ALL_dict, pfx_metrics_career_by_pitchtype
    )
    player_data = PlayerData(vig_app, 571882)
    assert player_data.pfx_pitching_metrics_for_career == pfx_metrics_vs_all_career
    assert player_data.percentiles_for_pitch_types_for_career
    assert player_data.pfx_pitching_metrics_vs_rhb_for_career
    assert player_data.percentiles_for_pitch_types_vs_rhb_for_career
    assert player_data.pfx_pitching_metrics_vs_lhb_for_career
    assert player_data.percentiles_for_pitch_types_vs_lhb_for_career
    assert player_data.pfx_pitching_metrics_by_year
    assert player_data.percentiles_for_pitch_types_by_year
    assert player_data.pfx_pitching_metrics_vs_rhb_by_year
    assert player_data.percentiles_for_pitch_types_vs_rhb_by_year
    assert player_data.pfx_pitching_metrics_vs_lhb_by_year
    assert player_data.percentiles_for_pitch_types_vs_lhb_by_year
    assert player_data.get_pfx_pitching_metrics_for_game(BBREF_GAME_ID)
    assert player_data.get_pfx_pitching_metrics_vs_rhb_for_game(BBREF_GAME_ID)
    assert player_data.get_pfx_pitching_metrics_vs_lhb_for_game(BBREF_GAME_ID)
    assert player_data.get_all_pfx_career_data()
    assert player_data.get_all_pfx_yearly_data()

    player_data = PlayerData(vig_app, 600303)
    assert player_data.pfx_batting_metrics_for_career
    assert player_data.pfx_batting_metrics_vs_rhp_as_lhb_for_career
    assert player_data.pfx_batting_metrics_vs_lhp_as_lhb_for_career
    assert player_data.pfx_batting_metrics_by_year
    assert player_data.get_pfx_batting_metrics_for_game(BBREF_GAME_ID)
    assert player_data.get_pfx_batting_metrics_vs_rhp_as_lhb_for_game(BBREF_GAME_ID)
    assert player_data.get_pfx_batting_metrics_vs_lhp_as_lhb_for_game(BBREF_GAME_ID)

    player_data = PlayerData(vig_app, 545361)
    assert player_data.pfx_batting_metrics_vs_rhp_as_rhb_for_career
    assert player_data.pfx_batting_metrics_vs_lhp_as_rhb_for_career
    assert player_data.get_pfx_batting_metrics_vs_rhp_as_rhb_for_game(BBREF_GAME_ID)
    assert player_data.get_pfx_batting_metrics_vs_lhp_as_rhb_for_game(BBREF_GAME_ID)
