from dacite.core import from_dict

from vigorish.data.team_data import TeamData
from vigorish.data.metrics import BatStatsMetrics, PitchStatsMetrics


def test_team_data(vig_app):
    away_pitch_stats_dict = {
        "mlb_id": 0,
        "year": 2019,
        "player_team_id_bbref": "LAA",
        "opponent_team_id_bbref": "",
        "stint_number": 0,
        "total_games": 1,
        "games_as_sp": 1,
        "games_as_rp": 4,
        "wins": 1,
        "losses": 0,
        "saves": 0,
        "innings_pitched": 9.0,
        "total_outs": 27,
        "batters_faced": 37,
        "runs": 5,
        "earned_runs": 5,
        "hits": 8,
        "homeruns": 3,
        "strikeouts": 8,
        "bases_on_balls": 3,
        "era": 5.0,
        "whip": 1.222,
        "k_per_nine": 8.0,
        "bb_per_nine": 3.0,
        "hr_per_nine": 3.0,
        "k_per_bb": 2.667,
        "k_rate": 0.216,
        "bb_rate": 0.081,
        "k_minus_bb": 0.135,
        "hr_per_fb": 0.231,
        "pitch_count": 129,
        "strikes": 81,
        "strikes_contact": 40,
        "strikes_swinging": 18,
        "strikes_looking": 23,
        "ground_balls": 13,
        "fly_balls": 13,
        "line_drives": 1,
        "unknown_type": 0,
        "inherited_runners": 2,
        "inherited_scored": 0,
        "wpa_pitch": 0.021,
        "re24_pitch": -0.2,
    }

    away_bat_stats_dict = {
        "mlb_id": 0,
        "year": 2019,
        "player_team_id_bbref": "LAA",
        "opponent_team_id_bbref": "",
        "stint_number": 0,
        "total_games": 1,
        "avg": 0.342,
        "obp": 0.422,
        "slg": 0.763,
        "ops": 1.185,
        "iso": 0.421,
        "bb_rate": 0.133,
        "k_rate": 0.133,
        "plate_appearances": 45,
        "at_bats": 38,
        "hits": 13,
        "runs_scored": 10,
        "rbis": 10,
        "bases_on_balls": 6,
        "strikeouts": 6,
        "doubles": 4,
        "triples": 0,
        "homeruns": 4,
        "stolen_bases": 0,
        "caught_stealing": 1,
        "hit_by_pitch": 0,
        "intentional_bb": 0,
        "gdp": 0,
        "sac_fly": 1,
        "sac_hit": 0,
        "total_pitches": 169,
        "total_strikes": 102,
        "wpa_bat": 0.479,
        "wpa_bat_pos": 0.606,
        "wpa_bat_neg": -0.128,
        "re24_bat": 5.2,
    }

    home_pitch_stats_dict = {
        "mlb_id": 0,
        "year": 2019,
        "player_team_id_bbref": "TOR",
        "opponent_team_id_bbref": "",
        "stint_number": 0,
        "total_games": 1,
        "games_as_sp": 1,
        "games_as_rp": 6,
        "wins": 0,
        "losses": 1,
        "saves": 0,
        "innings_pitched": 9.0,
        "total_outs": 27,
        "batters_faced": 45,
        "runs": 10,
        "earned_runs": 10,
        "hits": 13,
        "homeruns": 4,
        "strikeouts": 6,
        "bases_on_balls": 6,
        "era": 10.0,
        "whip": 2.111,
        "k_per_nine": 6.0,
        "bb_per_nine": 6.0,
        "hr_per_nine": 4.0,
        "k_per_bb": 1.0,
        "k_rate": 0.133,
        "bb_rate": 0.133,
        "k_minus_bb": 0.0,
        "hr_per_fb": 0.182,
        "pitch_count": 169,
        "strikes": 102,
        "strikes_contact": 60,
        "strikes_swinging": 10,
        "strikes_looking": 32,
        "ground_balls": 11,
        "fly_balls": 22,
        "line_drives": 9,
        "unknown_type": 0,
        "inherited_runners": 1,
        "inherited_scored": 0,
        "wpa_pitch": -0.478,
        "re24_pitch": -5.3,
    }

    home_bat_stats_dict = {
        "mlb_id": 0,
        "year": 2019,
        "player_team_id_bbref": "TOR",
        "opponent_team_id_bbref": "",
        "stint_number": 0,
        "total_games": 1,
        "avg": 0.235,
        "obp": 0.297,
        "slg": 0.5,
        "ops": 0.797,
        "iso": 0.265,
        "bb_rate": 0.081,
        "k_rate": 0.216,
        "plate_appearances": 37,
        "at_bats": 34,
        "hits": 8,
        "runs_scored": 5,
        "rbis": 5,
        "bases_on_balls": 3,
        "strikeouts": 8,
        "doubles": 0,
        "triples": 0,
        "homeruns": 3,
        "stolen_bases": 0,
        "caught_stealing": 0,
        "hit_by_pitch": 0,
        "intentional_bb": 0,
        "gdp": 2,
        "sac_fly": 0,
        "sac_hit": 0,
        "total_pitches": 129,
        "total_strikes": 81,
        "wpa_bat": -0.022,
        "wpa_bat_pos": 0.17,
        "wpa_bat_neg": -0.192,
        "re24_bat": 0.3,
    }

    away_team_data = TeamData(vig_app, "LAA", 2019)
    home_team_data = TeamData(vig_app, "TOR", 2019)
    assert away_team_data.team_pitch_stats == from_dict(data_class=PitchStatsMetrics, data=away_pitch_stats_dict)
    assert away_team_data.team_bat_stats == from_dict(data_class=BatStatsMetrics, data=away_bat_stats_dict)
    assert home_team_data.team_pitch_stats == from_dict(data_class=PitchStatsMetrics, data=home_pitch_stats_dict)
    assert home_team_data.team_bat_stats == from_dict(data_class=BatStatsMetrics, data=home_bat_stats_dict)
