"""Format strings used with strftime/strptime methods."""

DATE_ONLY = "%Y-%m-%d"
DATE_ONLY_2 = "%m/%d/%y"
DATE_ONLY_TABLE_ID = "%Y%m%d"
DT_NAIVE = "%m/%d/%y %I:%M:%S %p"
DT_AWARE = "%m/%d/%y %I:%M:%S %p %Z"
DT_STR_FORMAT = "%m/%d/%y %I:%M %p %Z"
DT_STR_FORMAT_ALL = "%Y-%m-%d %H:%M:%S.%f %Z%z"
DATE_MONTH_NAME = "%b %d %Y"
